### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by HJCFLY** [lossme/TencentComicBook#1]
![qq 20180424123605](https://user-images.githubusercontent.com/38662362/39166416-1b05e08e-47bc-11e8-9958-26adea1010d8.png)

**Comment by lossme** [comment]
id 写错了，没有 5004300 这个漫画 id
你想要的是不是 id=505430 这个漫画 http://ac.qq.com/Comic/ComicInfo/id/505430

**Comment by HJCFLY** [comment]
id写错了，后来我改正之后有如下情况：
![1](https://user-images.githubusercontent.com/38662362/39244513-6cddccc0-48c3-11e8-9b95-347715c95932.PNG)

**Comment by lossme** [comment]
`pip install onepiece`安装到的是其它包，跟我的这个有冲突，需要卸载 `pip uninstall onepiece`

**Comment by coremaya** [comment]
鼠绘全职猎人报错
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Downloads\1\TencentComicBook-master\onepiece\__main__.py", line 4, in <module>
    main()
  File "D:\Downloads\1\TencentComicBook-master\onepiece\cli.py", line 72, in main
    for data in task:
  File "D:\Downloads\1\TencentComicBook-master\onepiece\site\ishuhui.py", line 90, in get_task_chapter
    comic_title, all_chapter = self.get_all_chapter(comicid)
  File "D:\Downloads\1\TencentComicBook-master\onepiece\site\ishuhui.py", line 70, in get_all_chapter
    chapter_number = int(key.replace('n-', ''))
ValueError: invalid literal for int() with base 10: 'c-1-1-8'

**Comment by lossme** [comment]
鼠绘猎人报错已修复
