### ISSUE TITLE
关于合成PDF的BUG

### ISSUE THREAD

**Issue by sky137818221** [lossme/TencentComicBook#11]
下载B站漫画时 有一些漫画没有章节标题 合成PDF时 默认会找 章节序号+2个空格 的目录 搜索不到 不能合成PDF
另外一个类似的是超炮的漫画 也是没有章节标题
另外 非常感谢作者的脚本！
----------------------------------------------------------以下是LOG-------------------------------------------------------
2020/03/27 08:24:18 onepiece.logs [INFO] 正在获取最新数据
2020/03/27 08:24:20 onepiece.logs [INFO] 哔哩哔哩漫画 【铁臂阿童木前传】 更新至: 59 【 】 数据来源: https://manga.bilibili.com/m/detail/mc26521
2020/03/27 08:24:23 onepiece.logs [INFO] 正在下载 【铁臂阿童木前传】 1 【 】
2020/03/27 08:24:41 onepiece.logs [ERROR] [Errno 2] No such file or directory: './download/哔哩哔哩漫画/铁臂阿童木前传/1  '
Traceback (most recent call last):
  File "/home/sky/TencentComicBook/onepiece/cli.py", line 156, in main
    pdf_path = chapter.save_as_pdf(output_dir=output_dir)
  File "/home/sky/TencentComicBook/onepiece/comicbook.py", line 117, in save_as_pdf
    sort_by=lambda x: int(x.split('.')[0]))
  File "/home/sky/TencentComicBook/onepiece/utils/img2pdf.py", line 45, in image_dir_to_pdf
    img_path_list = sorted(os.listdir(img_dir), key=sort_by)
FileNotFoundError: [Errno 2] No such file or directory: './download/哔哩哔哩漫画/铁臂阿童木前传/1  '
2020/03/27 08:24:44 onepiece.logs [INFO] 正在下载 【铁臂阿童木前传】 2 【 】
2020/03/27 08:24:58 onepiece.logs [ERROR] [Errno 2] No such file or directory: './download/哔哩哔哩漫画/铁臂阿童木前传/2  '
Traceback (most recent call last):
  File "/home/sky/TencentComicBook/onepiece/cli.py", line 156, in main
    pdf_path = chapter.save_as_pdf(output_dir=output_dir)
  File "/home/sky/TencentComicBook/onepiece/comicbook.py", line 117, in save_as_pdf
    sort_by=lambda x: int(x.split('.')[0]))
  File "/home/sky/TencentComicBook/onepiece/utils/img2pdf.py", line 45, in image_dir_to_pdf
    img_path_list = sorted(os.listdir(img_dir), key=sort_by)
FileNotFoundError: [Errno 2] No such file or directory: './download/哔哩哔哩漫画/铁臂阿童木前传/2  '

**Comment by lossme** [comment]
已更新修复

**Comment by sky137818221** [comment]
非常感谢！
