### ISSUE TITLE
作者你好，请问加入"漫画柜"的api采集吗？谢谢

### ISSUE THREAD

**Issue by chuihai** [lossme/TencentComicBook#23]
这个是漫画柜的网址‘https://www.manhuagui.com/’号称台湾地区最好的日漫网址！我看了有些人写关于“漫画柜“的采集方法 
‘https://blog.csdn.net/weixin_40352715/article/details/105548053’但是没有尝试成功 ！谢谢

**Comment by lossme** [comment]
已经加上了，更新试下吧

**Comment by 8108905** [comment]
不知道为什么我从新安装后 启动api这样提示！ 下载漫画没问题，但是使用api有问题 谢谢作者

`jason@MacBook-Pro TencentComicBook % gunicorn 'api:create_app()' -b "127.0.0.1:8000" --workers=2 --timeout=30
[2020-10-13 18:11:34 -0700] [31561] [INFO] Starting gunicorn 20.0.4
[2020-10-13 18:11:34 -0700] [31561] [INFO] Listening at: http://127.0.0.1:8000 (31561)
[2020-10-13 18:11:34 -0700] [31561] [INFO] Using worker: sync
[2020-10-13 18:11:34 -0700] [31563] [INFO] Booting worker with pid: 31563
[2020-10-13 18:11:34 -0700] [31564] [INFO] Booting worker with pid: 31564
[2020-10-13 18:11:34 -0700] [31563] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/util.py", line 411, in import_app
    app = app(*args, **kwargs)
  File "/Users/jason/Documents/wwwroot/TencentComicBook/api/__init__.py", line 12, in create_app
    from .views import app as main_app
  File "/Users/jason/Documents/wwwroot/TencentComicBook/api/views.py", line 10, in <module>
    from onepiece.comicbook import ComicBook
  File "/Users/jason/Documents/wwwroot/TencentComicBook/onepiece/comicbook.py", line 12, in <module>
    from .crawlerbase import CrawlerBase
  File "/Users/jason/Documents/wwwroot/TencentComicBook/onepiece/crawlerbase.py", line 5, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'
[2020-10-13 18:11:34 -0700] [31563] [INFO] Worker exiting (pid: 31563)
[2020-10-13 18:11:34 -0700] [31564] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gunicorn/util.py", line 411, in import_app
    app = app(*args, **kwargs)
  File "/Users/jason/Documents/wwwroot/TencentComicBook/api/__init__.py", line 12, in create_app
    from .views import app as main_app
  File "/Users/jason/Documents/wwwroot/TencentComicBook/api/views.py", line 10, in <module>
    from onepiece.comicbook import ComicBook
  File "/Users/jason/Documents/wwwroot/TencentComicBook/onepiece/comicbook.py", line 12, in <module>
    from .crawlerbase import CrawlerBase
  File "/Users/jason/Documents/wwwroot/TencentComicBook/onepiece/crawlerbase.py", line 5, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'
[2020-10-13 18:11:34 -0700] [31564] [INFO] Worker exiting (pid: 31564)
[2020-10-13 18:11:34 -0700] [31561] [INFO] Shutting down: Master
[2020-10-13 18:11:34 -0700] [31561] [INFO] Reason: Worker failed to boot.
jason@MacBook-Pro TencentComicBook % 
`

**Comment by lossme** [comment]
需要更新依赖 `pip install requirements.txt`

**Comment by 8108905** [comment]
谢谢  ！ http://127.0.0.1:8000/api/manhuagui/comic/19430/  这个ok  ，
http://127.0.0.1:8000/api/manhuagui/comic/19430/2  章节内容 500 错误  

谢谢

**Comment by 8108905** [comment]
如果方便的话 ，可以给所有漫画加入一个 连载状态，例如 连载中 已完结  谢谢

**Comment by 8108905** [comment]
http://127.0.0.1:8000/api/wnacg/comic/106789  这个没有封面
