### ISSUE TITLE
 Please read on bilibili Manga APP 【bilibili改版，只能用app看漫画的报错】

### ISSUE THREAD

**Issue by hadhe145** [lossme/TencentComicBook#37]
请输入要下载的comicid: 26505
2020/12/10 11:11:26 onepiece.cli 223 [INFO] 正在获取最新数据
2020/12/10 11:11:26 onepiece.cli 234 [INFO] 哔哩哔哩漫画 【咒术回战】 更新至: 134 【涉谷事变㊾】 数据来源: https://manga.bilibili.com/m/detail/mc26505
2020/12/10 11:11:26 onepiece.cli 169 [ERROR] download comicbook error. site=bilibili comicid=mc24742 chapter_number=134
Traceback (most recent call last):
  File "/home/jw/Documents/codes/TOOLS/TencentComicBook-master/onepiece/cli.py", line 146, in download_main
    chapter = comicbook.Chapter(chapter_number, ext_name=ext_name)
  File "/home/jw/Documents/codes/TOOLS/TencentComicBook-master/onepiece/comicbook.py", line 123, in Chapter
    chapter_item = self.crawler.get_chapter_item(citem)
  File "/home/jw/Documents/codes/TOOLS/TencentComicBook-master/onepiece/site/bilibili.py", line 129, in get_chapter_item
    chapter_api_data = self.get_chapter_api_data(cid=citem.cid)
  File "/home/jw/Documents/codes/TOOLS/TencentComicBook-master/onepiece/site/bilibili.py", line 81, in get_chapter_api_data
    raise ChapterNotFound(f"Please read on bilibili Manga APP. {source_url}")
onepiece.exceptions.ChapterNotFound: Please read on bilibili Manga APP. https://manga.bilibili.com/mc26505/520833

请问这个能更新修复吗？

**Comment by hadhe145** [comment]
原因为，第零话未购买，从第一话开始下载无问题
