### ISSUE TITLE
网易漫画下载报错：onepiece.exceptions.ComicbookNotFound: 资源未找到

### ISSUE THREAD

**Issue by zhpking** [lossme/TencentComicBook#5]
漫画源
https://163.bilibili.com/source/4614683956320127821

命令
sudo python3 -m onepiece --site=wangyi --comicid=4617223306170106231 --all

错误信息
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/htdocs2/TencentComicBook-master/onepiece/__main__.py", line 4, in <module>
    main()
  File "/opt/htdocs2/TencentComicBook-master/onepiece/cli.py", line 135, in main
    comicbook = ComicBook.create_comicbook(site=site, comicid=comicid)
  File "/opt/htdocs2/TencentComicBook-master/onepiece/comicbook.py", line 45, in create_comicbook
    return cls(comicbook_crawler=crawler)
  File "/opt/htdocs2/TencentComicBook-master/onepiece/comicbook.py", line 25, in __init__
    self.comicbook_item = self.crawler.get_comicbook_item()
  File "/opt/htdocs2/TencentComicBook-master/onepiece/site/wangyi.py", line 56, in get_comicbook_item
    raise ComicbookNotFound(msg)
onepiece.exceptions.ComicbookNotFound: 资源未找到！ site=wangyi comicid=4617223306170106231

网易漫画域名换了，从原本的manhua.163.com改成163.bilibili.com，曾试过把wangyi.py文件中的域名替换成163.bilibili.com，但还是报这个错误...

**Comment by lossme** [comment]
针对网易漫画域名的变更，已做更新修复，请下载最新的代码。
另外命令里的comicid写错了

**Comment by zhpking** [comment]
难怪一直报错。。。下载最新代码能成功下载了，工具很方便很实用！
